#!/bin/bash
#
plugin="recycle.bin"

# Read in the configuration.
CONFIG="/boot/config/plugins/${plugin}/${plugin}.cfg"
source $CONFIG

# Start recycle bin if it is enabled.
if [ "$SERVICE" = "enable" ]; then
	/usr/local/emhttp/plugins/${plugin}/scripts/rc.${plugin} start 30 1>/dev/null &
fi
