#!/bin/bash
#
plugin="recycle.bin"

# Stop recycle bin if it is running.
/usr/local/emhttp/plugins/${plugin}/scripts/rc.${plugin} stop shutdown 1>/dev/null

# Remove RecycleBin browse symlinks.
rm -rf /mnt/RecycleBin

# Remove cron file
rm -rf /boot/config/plugins/${plugin}/recyclebin.cron
