#!/bin/bash
#
plugin="recycle.bin"

# Stop recycle bin if it is running.
if [ -e "/var/run/${plugin}/${plugin}.pid" ]; then
	/usr/local/emhttp/plugins/${plugin}/scripts/rc.${plugin} stop shutdown
fi

# Remove RecycleBin browse symlinks.
rm -rf /mnt/RecycleBin
