#!/bin/bash
source /boot/config/plugins/vfs_recycle/vfs_recycle.cfg

# Stop vfs recycle
/etc/rc.d/rc.vfs_plg stop

# Update the valid users and parameters in the smb-extra.conf file
/etc/rc.d/rc.vfs_plg smb

# Start vfs recycle if service is enabled
if [[ $SERVICE = "enable" ]]; then
	/etc/rc.d/rc.vfs_plg start
fi
